apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: custom
spec:
  generic:
    example:
      insecure: true
      url: "10.0.1.1:8080"
      config: |-
        key1: value1
        key2: value2

